package br.com.eventhorizon.common.pa.test;

public enum PATestType {

  TRIVIAL_SOLUTION_WITH_SIMPLE_DATASET_TEST,
  FINAL_SOLUTION_WITH_SIMPLE_DATASET_TEST,
  MEMORY_LIMIT_TEST,
  TIME_LIMIT_TEST,
  STRESS_TEST,
  COMPARE_TEST;
}
